Steamodded/smods

core/sprite.lua
Without this change the "atlas" variable only does something the SECOND time set_sprites is called, and this code is only needed to exist once generically alongside being generic itself so there is no real reason not to have it within steamodded itself
=> Added a function wrapper to set_sprites to allow Jokers to have custom atlases without jank

.gitignore, core/core.lua
There is a request thread open on Discord asking to have the Mods menu updated to better handle large mod lists.
This PR adds a page selector to the menu whenever there is at least 1 mod active. The menu will now display 4 mods per page and allow the player to go through the pages to see all their loaded mods.
Additionally, the code used to generate and update a dynamic menu pane has been implemented in a way that should be reusable by other modders. I've tried to add some comments to explain how it works with the Mods menu as an example.
Here are some screenshots of the updated Mods menu:
=> Add page selector for mods list

example_mods/AbsoluteDeck.lua
Adding tooltip usage to one of the example mods to show other modders how it could be used.
=> Adding polyglass tooltips to Absolute Deck

loader/loader.lua
This PR adds the option of modders to specify an integer priority value by appending a line to the Steamodded header as such:
```lua
--- PRIORITY: -100
```
Both the loading of mod files and execution of init functions have been adapted to adhere to an ordering of mods from lowest to highest priority values, i.e., a high negative priority value will cause your mod to be loaded first. Mods that don't specify a priority value are assigned a default value of 0, with the loading order of mods with equal priority staying unchanged.
=> Add priority system to loader

core/suit.lua
Fixes: 
- Fix a bug with get_straight deviating from the base game's behavior, not allowing five card straights with four fingers
- Fix an issue with is_face not accounting for stone cards properly, causing stone cards that were face cards originally to be considered face cards
- Address an issue where added playing cards are unloaded on profile/language change.
Known issues:
- The playing card API currently does not offer multi-language support, and any information inserted regarding new playing cards is erased when changing languages. This will be implemented at a later date.
=> Playing Card API bug fixes

core/core.lua, core/joker.lua, core/sprite.lua, core/suit.lua
- Allows usage of the `effect` field with custom jokers, as well as explicit passing of an atlas, to allow all jokers of a mod to share an atlas.
- As a result, the `effect` method previously used for the `set_ability` function was renamed to `set_ability` to be more descriptive and ensure compatibility.
- An interface for `Card:generate_UIBox_ability_table` has been introduced in the form of `SMODS.Joker:loc_def` to reduce boilerplate.
- Fix visual issues with undiscovered modded jokers in the collection
=> Fixes / utility for joker API

lovely.toml
Fixes a crash when using lovely.
=> fix: add StackTracePlus.lua to lovely.toml

debug/tk_debug_window.py
Added the folowing shortcuts:
- `Shift + Enter` when focused on the search bar: Go to the previous search result.
- `Ctrl + S`: Save all logs to a file.
- `Ctrl + Shift + S`: Save filtered logs to a file.
- `Ctrl + D`: Clear all logs.
- `Ctrl + L`: Focus the logger filter.
=> Debug console QoL shortcuts

core/StackTracePlus.lua
This PR modifies the better stack trace, to use its own implementation for rendering the error. This provides the following benefits
- No more hacks to show the stack trace (and it has consistent output whether or not the user has debug mode enabled)
- Won't send crash logs to localthunk
- Log can be copied with ctrl + c
- Log can be scrolled if its too big for the screen
- Now shows some other info, which might help in debugging. Namely: Balatro Version, Steamodded Version, Lovely Version (if applicable), list of steamodded mods.
- Much easier to add more functionality in the future, if we so desire
I've also made a new api. Mod's can now set SMOD.DebugInfo.modid to either a string, or table of strings, and the crash handler will display them beneath the mod. This is designed for mods to …
=> Fully custom error handler

core/StackTracePlus.lua, loader/loader.lua, lovely/core.toml
This adds some improvements to the crash handler. Namely:
Arrows indicating when you can scroll (a lot of people didn't realize you could. Hopefully this helps)
https://github.com/Steamopollys/Steamodded/assets/33164598/62ae8f04-0ff4-4446-91c0-5f6c0d922249
Loads the crash handler much sooner. I made it init itself immediately after injecting, and also caused it to be injected sooner (I tried loading it before core, but then it threw an error about the filesystem not being initalized, if there was an error in core, so I just let it be after).
A few minor cleanups.
=> Crash handler improvements

core/game_object.lua, core/sound.lua
Inversed to :
```
if string.find(s.sound_code,'music') then
sound_vol = sound_vol * (G.SETTINGS.SOUND.music_volume / 100.0)
else
sound_vol = sound_vol * (G.SETTINGS.SOUND.game_sounds_volume / 100.0)
end
```
Instead of : 
```
if string.find(s.sound_code,'music') then
sound_vol = sound_vol * (G.SETTINGS.SOUND.game_sounds_volume / 100.0)
else
sound_vol = sound_vol * (G.SETTINGS.SOUND.music_volume / 100.0)
end
```
=> Sound API used the wrong sound setting

core/StackTracePlus.lua, loader/loader.lua
This improves the error message 
`--- STEAMODDED HEADER...:25: Funny Crash go BRRRRRRRRRRR` > `[SMODS Crashing "Crashing.lua"]:25: Funny Crash go BRRRRRRRRRRR`
For the name, the vars are `<const SMODS> <Mod ID> "<Mod filename>"`. 
A side effect of this is the mod in the stack trace is a bit different. 
```
(4) Lua method 'key_press_update' at line 25 of mod Crashing (Crashing) 
Local variables:
self = table: 0x047af920  {dragging:table: 0x047afaa0, pressed_keys:table: 0x047affe0, held_keys:table: 0x047b0540 (more...)}
key = string: "["
dt = number: 0.0210579
```
to
```
(4) Lua method 'key_press_update' at file 'Crashing.lua:25' (from mod with id Crashing)
Local variables:
self = table: 0x042e6258  {lock_input:false, clicked:table: 0x044c0fb0, focused:table: 0x04412c50 (more...)}
key = …
```
=> Better error chunk names

lovely/back.toml, lovely/center.toml, lovely/payout_arg.toml
Adds a couple misc functions
- `trigger_effect`: Used by decks to calculate active effects through the `Back:trigger_effect` function (used by Anaglyph and Plasma Deck). 
- `reset_game_globals`: Used for setting global variables that chance per round (such as the suit/rank globals used by Jokers like Mail-in Rebate, The Idol, etc.). `first_pass` is to check for if the function is called when `Game:start_run` is. 
- `set_debuff`: Used to add custom logic for debuffing cards. 
Also moved `calc_dollar_bonus` from payout_lua lovely file into center lovely file because nobody noticed it existed xdd.
=> Add a few QoL functions

lovely/fixes.toml
This pr adds a check to the game that prevents it from crashing when pressing the play button with an invalid/corrupted save.jkr, allowing people to make a new game. This is technically a balatro bug, but invalid saves are more common when using mods, so I figured it would be nice to fix.
A before and after:
https://github.com/Steamopollys/Steamodded/assets/33164598/db323baf-b68b-47c5-95bf-3c1210c6d1ae
Ping me on discord if you want a corrupt save to test with (github doesn't let me upload .jkr files)
=> feat: prevent crash with corrupt/invalid saves

lovely/booster.toml
Opting out of the more universal but more potentially destructive option of setting all cards' price to 0 if it's in a booster pack through `set_cost()` because all other base game objects circumvents this issue. Only vouchers don't.
=> Make Vouchers earned from booster packs not cost money

core/core.lua, core/game_object.lua, core/utils.lua, example_mods/Mods/NegateTexturePack/NegateTexturePack.lua, loader/loader.lua
Allows for consistent configuration of key prefixing across all classes (#144).
Changes `card_key` for suits and ranks to comply with this. This field is no longer subject to automatic decollisioning and uses mod prefixes exclusively for this purpose.
TODO:
- ~~`SMODS.GameObject:take_ownership()` is currently a huge mess. We need to find a better way to integrate it into this new system.~~
=> Rationalize prefixes

core/StackTracePlus.lua, lovely/core.toml, lovely/crash_handler.toml
This PR makes some improvements to the crash handler. Most notably:
- Improve reliability, but not assuming some things are always avaible.
- Injecting the crash handler at the beginning of the main lua file, to catch more errors (and completly disabling the built in one)
- Adds a note that esc exits the game (as the game can get stuck in fullscreen if it crashes too early)
- Adds a note that restarting the game breaks lovely (hopefully we can get this fixed soon)
As an aside, you can change the target of the copy patch to `'=[love "wrap_Event.lua"]'` to hook an internal love function, and get the handler loaded before love even try's loading the main file. This allows it to catch syntax errors, but this does seem kinda hacky, and lovely throws an error trying to dump that file, so idk if …
=> feat: improve crash handler reliability, and load sooner

core/utils.lua
`SMODS.restart_game` now respects spaces in file path when trying to restart the exe.
=> Fix space issue in path when restarting

core/overrides.lua, example_mods/Mods/EditionExamples/EditionExamples.lua, example_mods/Mods/EditionExamples/assets/shaders/anaglyphic.fs, example_mods/Mods/EditionExamples/assets/shaders/flipped.fs, example_mods/Mods/EditionExamples/assets/shaders/fluorescent.fs, example_mods/Mods/EditionExamples/assets/shaders/foil.fs, example_mods/Mods/EditionExamples/assets/shaders/gilded.fs, example_mods/Mods/EditionExamples/assets/shaders/greyscale.fs, example_mods/Mods/EditionExamples/assets/shaders/ionized.fs, example_mods/Mods/EditionExamples/assets/shaders/laminated.fs, example_mods/Mods/EditionExamples/assets/shaders/monochrome.fs, example_mods/Mods/EditionExamples/assets/shaders/overexposed.fs, example_mods/Mods/EditionExamples/assets/shaders/sepia.fs, lovely/edition.toml, lovely/fixes.toml, lovely/number_formatting.toml, lovely/ui.toml
**Edition improvements**
1. ARGS.send_to_shader[1] no longer infinitely increases (which makes it much easier to use in shaders). I have tested vanilla shaders running with this change for over an hour and they're doing fine.
2. edition.override_shape - edition parameter that allows shaders to change shape of the card without "default" card layer being rendered below it.
before change:
after change:
3. edition.no_shadow - small feature to disable shadows for shaders
**Number formatting fixes**
1. Display infinity properly (used to show `nan e 0`)
2. Remove trailing zeroes (e.g. `1.5` would get formatted to `1.50`, `1.001` to `1`)
3. Fix negative money formatting (-100 used to be -,100)
4. Scientific notation for negative money (by Wilsonthewolf, I just improved a few things)
**Performance …
=> Edition improvements, number formatting fixes, small performance fix and UI tab triangles fix

core/utils.lua, lovely/seal.toml
Adds `poll_seal` instead of hardcoded values or `rng_buffer`. Allows seals to have a `weight` value, and also respects `in_pool` results if called without a set of options.
Added custom sounds to seals when they are applied. Defaults to vanilla sound.
=> Seal weights and sounds

core/game_object.lua
Added a support for meteor particles, as the current `SMODS.Booster.update_pack` only handles sparkles
=> Add a meteor particle support to Booster API

core/overrides.lua, example_mods/Mods/EditionExamples/EditionExamples.lua, example_mods/Mods/EditionExamples/README.md, lovely/edition.toml, lovely/fixes.toml
Small tweaks with new edition options, and fix options not saving on save reload.
And updated readme for edition examples.
Can you also update wiki with `disable_base_shader` and `disable_shadow` parameters?
`disable_base_shader` - removes default shader applied to the card - `booster` (spectral cards, booster packs), `voucher` (invisible joker, vouchers) and `dissolve` (everything else). Easier to understand with example, you can use screenshots from [here](https://github.com/Steamopollys/Steamodded/pull/220).
Enable this if your shader modifies card transparency or shape in any way.
`disable_shadow` - disables shadow drawn under the card.
It would also make sense if the wiki pointed towards example mods folder as well as README in edition examples.
Or simply copy useful information from …
=> Some more edition changes

core/game_object.lua
Using a simple mod that replaces stickers with smaller versions (Less Intrusive Stickers by FabianPEKS) by replacing the stickers.png Atlas, non-stake stickers show as doubled:
This change fixes the issue by injecting the respective global variables in the Sticker object. This was the quickest and most obvious way I could see to fix the problem, but my experience with Lua and this game are low so let me know if you have requested changes. Thanks!
=> Add injection for eternal/perishable/rental globals

core/StackTracePlus.lua
This improves the logic for handling lovely mods in the crash handler. Most notably, lovely mods now show up when the game crashes while loading mods, and lovely mods now show up for SMODS mods that couldn't load (missing dependencies for example).
=> feat: crash handler better lovely mods

core/game_object.lua
Fixes #198:
- Moves descriptions for seals out to match those of enhancements/editions (name/text/label all at top level)
- Move names for Ranks and Challenges into `loc_txt.name` so loc_txt is consistently a table
Fixes #210:
- Removes the extra prefix The Wheel's text sometimes has
=> Loc text consistency

core/game_object.lua, core/overrides.lua, lovely/edition.toml
Should be added to wiki:
SMODS.Atlas
`disable_mipmap` - disable mipmap being applied to this texture
SMODS.Edition
`shader = false` support. Shaderless editions can use 2 new functions:
`on_apply = function (card)` - run when edition is applied to a card
`on_remove = function (card)` - run when edition is removed from the card
=> Mipmap fixes and more shaders stuff

core/game_object.lua, core/overrides.lua
Fix rental sticker not being applied on gold stake
Fix stakes not unlocking on decks that haven't been used prior to recent changes
=> few bug fixes

core/overrides.lua
This fixes a crash when using 1 or 2 key with debug mode on a blind. Note if you want to test the fix, you can't use DebugPlus, as it crashes in another spot due to this change.
=> fix: crash when unlocking/discovering blind

core/overrides.lua
This is the same as #253, it just turns out that this code is done twice, and still crashes on the second page.
=> fix: crash when unlocking/discovering blind... again

core/overrides.lua
This removes a local variable discovered, using the reference value. This allows me to alter the popup of a blind when debug unlocking it in DebugPlus (which I couldn't do in the base game without a lovely patch).
=> feat: reference blind discovered

core/game_object.lua, core/overrides.lua, example_mods/Mods/EditionExamples/EditionExamples.lua, example_mods/Mods/EditionExamples/README.md, example_mods/Mods/EditionExamples/assets/shaders/flipped.fs, example_mods/Mods/EditionExamples/assets/shaders/gold.fs, lovely/edition.toml
`send_vars = function (sprite)` - support custom external vars to be sent to shader. 
If a table is returned, `Shader:send(key, value)` will be run for every table entry.
Usage example:
`mod.lua`
```
SMODS.Shader {
key = 'chromatic',
path = 'chromatic.fs',
send_vars = function (sprite)
return {
test = 123,
}
end
}
```
`chromatic.fs`
```
...
extern vec2 chromatic;
extern float test;
...
```
=> SMODS.Shader - optional method for custom external vars

core/game_object.lua, core/overrides.lua
- fix stake duplication when take_ownership is used
- attempt to fix `nil` crash when calling `get_deck_win_stake()`
- allow Tags to not require loc_vars
=> Stake and Tag fixes

core/StackTracePlus.lua
This shows in the crash handler when a lovely mod has a steamodded part that failed to load. This does not show purely steamodded mods that failed to load, as they are not going to cause crashes.
=> feat: show fail in crash handler

core/utils.lua
Fixes non-default objects (any object in `G.P_CENTERS` that is not a Joker/Back/Edition/Consumable/Booster Pack/Voucher) from not getting properly unlocked on boot.
Doing a quick search for `SMODS.SAVE_UNLOCKS` on github ([link](https://github.com/search?q=SMODS.SAVE_UNLOCKS&type=code&p=1)) I cannot find any direct conflicts with this change. I have not tested whether any changes happen to the savefile, but I expect no breakage.
=> Fix SMODS.SAVE_UNLOCKS() key restriction

lovely/joker_retrigger.toml
Blueprint and Brainstorm (and any custom jokers that use similar methods) display their status text on the card they are copying. These patches should fix this to make the message appear under the blueprint/brainstorm card instead.
=> Fix bp/bs messages

lovely/stake.toml
Hopefully the final fix for the `wins_by_key` error. Modifies the `set_deck_loss` function. 
With help from Eremel and ItsFlowwey.
Was able to replicate the crash without this patch, can no longer replicate it after applying the patch.
=> Lovely fix for wins_by_key error caused by set_deck_loss

core/ui.lua
Steamodded would restart the entire game when closing the mods menu, because/if no mods were found.
Now checks if the delta mods counter actually exists before restarting.
=> Fix restart when no mods are found

lovely/pool.toml
`pseudorandom_element` function always called the rank and suit' `in_pool` function with the argument `{initial_deck = true}` regardless of where it's called (eg: during standard packs, shops with Magic Tricks vouchers)
I have added an extra check if it's called from Erratic Deck population step as well. In such case, it should also have `{initial_deck = true}` argument too.
=> Bug Fix: in_pool function for Rank and Suit

core/game_object.lua, core/utils.lua, lovely/edition.toml
- Editions `extra_cost` value ignored `G.GAME.inflation`
- Enhancements that provide bonus chips have their values seperated from permanent bonus effects, such as Hiker
- Added `SMODS.poll_enhancement` *(follows same structure as other poll functions)*
- Renamed `name` in `SMODS.poll_seal` to `key` *(will break current uses of function with defined options as `{name:weight}` paired tables)*
=> Enhancement clean ups

core/game_object.lua, lovely/deck_skins.toml
Adds DeckSkin as a GameObject and provides an API for mods to add deck skins.
The API accepts:
- key - The identifying key.
- suit - The suit this DeckSkin applies to.
- ranks - The ranks this DeckSkin supports.
- lc_atlas - The name of the atlas used for the DeckSkin's low contrast texture.
- hc_atlas - Optional - The name of the atlas used for the DeckSkin's low contrast texture. If missing the lc_atlas will be used instead.
- posStyle - Optional - Determines the way cards in the textures are accessed. If 'collab' positions will be taken from G.COLLABS.pos, which matches the current layout of Balatro's collabs. If 'deck' positions will be taken from the card's pos, which matches the current layout of the deck texutre. if 'suit' the y position will be 0 and the x position will be taken …
=> Deck Skins

core/overrides.lua
Fixes situations where creating negative cards results in a negative handsize after playing or discarding them
Repro case:
- Start a new game
- Use debug tools to mark a card as negative. Hand size is now 9/9 as a new card is drawn.
- Discard the negative card. Hand size is now 8/8 as expected.
- Make another negative card and discard it. Hand size is now 8/7. Hand size is permanently reduced.
This appears to be happening because discarding a negative card updates real_hand_size, where creating a new negative card doesn't.
=> Update real_card_limit when creating negative (playing) card

example_mods/Mods/DeckSkinTemplate/DeckSkinTemplate.lua
This template should simplify the DeckSkin creation process for less code-savvy users.
Instructions:
1. **Create playing card textures** for each suit in a single file, organized as in the base game. **From top to bottom:** Hearts, Clubs, Diamonds, and Spades. **From left to right:** in rank order, starting from 2 and ending at Ace. **Optional:** make a high-contrast version of the texture;
2. **Put** the normal and double-sized **textures in folders** `…/assets/1x` and `…/assets/2x`, respectively;
3. **Rewrite the header** as desired;
4. **Edit the variables below the header** to match (filename as saved in the assets, prefix as defined in the header, etc.);
5. **Enjoy!**
=> Create DeckSkinTemplate as an example mod

core/game_object.lua
The omit field in the default game is normally used for omitting the challenge deck from the center_pools table, however steamodded did not take this into account. I fixed this issue by just checking whether the field is true or not and also adding a new explicit field to the Back constructor.
=> Fix omit field not registering

lovely/joker_retrigger.toml
When Blueprint copied Brainstorm or Brainstorm copied Blueprint, they'd duplicate the effect because of no_callback being set to false by the Joker being copied.
This fixes that bug ( #301 )
Before:
https://github.com/user-attachments/assets/45266fcd-0eee-4e0e-be7b-cd6193e1ea7c
After:
https://github.com/user-attachments/assets/7fa0f5e5-0093-4d1f-a187-02c40dd4aca2
=> Fix blueprint and brainstorm copying eachother duplicating effects

loader/loader.lua
:zany_joker:
Fixes steamodded not being able to load mod when json metadata file fails to provide (the optional) dependencies or conflicts fields.
=> Allow empty inputs for deps/conflicts in json metadata

lovely/achievements.toml
Somehow I managed to easily figure out how to fix the issue where SMODS achievements stopped being able to be unlocked after MathIsFun's commit to fix a memory leak issue. Never doubting my coding abilities again
=> Fixed SMODS achievements not unlocking

lovely/atlas.toml
Allows centers affected by `SMODS.UndiscoveredSprite` to ignore it and use their own custom undiscovered sprite handling, using the `undiscovered` table.
=> Individual Undiscovered Sprite

lovely/fixes.toml
In the same way that h_mult adds mult for cards, h_chips does the same for chips. This is at the current moment not possible to do without lovely patching (to my knowledge). Normalizing this mitigates conflicts.
=> Adds h_chips as a viable return value for cards in hand playarea

lovely/fixes.toml
idk maybe it works
if it doesn't break anything, this fixes pack skip button not being active when no cards left in pack, and pack skipping too fast and causing cards to go unassigned
=> attempt to fix booster skip issues

src/overrides.lua
Whoops. Should've caught this the first time I fixed issues with this part of the code. Would've sent this in sooner but life got in the way.
Repro:
- Open a tarot or spectral pack
- Make a playing card negative (DebugPlus or Cryptid's 'Ritual' spectral card)
- Hand size is permanently reduced by 1
=> Fix hand size reduction caused by negative playing cards in tarot packs

src/game_object.lua
There is a bug where `take_ownership` does not reset the `orig_o.generate_ui` value when the object ownership was taken the second time, so it keeps calling the vanilla localization function despite SMODS side having one.
=> fix take_ownership bug

src/logging.lua, tk_debug_window.py
Port 12345 is used by a lot of different random things, so the risk of port collisions causing the debug console to conflict with some other software is relatively high. Changing it to another port that's not so commonly used should make that a lot less likely
=> change debug port to one with fewer collisions

lovely/back.toml, lovely/better_calc.toml
Adds context.individual and context.other_joker/other_consumeable as evaluated contexts for decks. Also introduces `SMODS.Back.calculate` and deprecates `SMODS.Back.trigger_effect` to indicate consistency with other calculate functions. This calculate function as well as `SMODS.Back.apply` get passed the `Back` they're called on, again for consistency
=> More deck contexts, SMODS.Back.calculate

lovely/better_calc.toml
All other instances of get_edition have been replaced with calculate_edition, respecting Edition.take_ownership.calculate, this one is missing
On that note, since it seems to me that all other instances of get_edition() has been fully eliminated and replaced with calculate_edition, I'm not sure I understand why overrides.lua:1474 has been commented out.
=> fix: main scoring on card still using get_edition

lovely/joker_size.toml
Adds the ability to set the size of jokers through parameters  
`pixel_size` controls how large the joker's sprite is considered. Ex: half joker would set `pixel_size.h` to indicate that it has a smaller sprite. defaults to `{ w = 71, h = 90 }`  
`display_size` controls how the joker's sprite is scaled. Ex: wee joker would set both `display_size.h` and `display_size.w` to indicate that it should be shrunk. defaults to `pixel_size`  
partial tables can also be used, with the default being used for missing values  
`pixel_size` and `display_size` can be combined and both work as normal  
in other words, `display_size` controls the bounding box of the joker, and `pixel_size` controls the portion of the sprite that it fit to the bounding box  
WARNING! stake stickers look broken on narrow & …
=> Add Easy Joker Resizing

src/ui.lua
The goal of this PR is to allow for mods `config.lua` file to make use of nested values.
Consider the following:
For sake of example, lets say I have the following as my `config.lua` file for my mod:
```lua
return {
["foo_group_1"] = {
["money"] = 10,
["enabled"] = true,
},
["foo_group_2"] = {
["yellow"] = {
["label"] = "cat",
["enabled"] = false,
},
},
}
```
Lets say the player uses the mod config menu to edit the settings of the mod to make the following table be our current saved config for the mod:
```lua
{
["foo_group_1"] = {
["money"] = 23,
["enabled"] = true,
},
["foo_group_2"] = {
["yellow"] = {
["label"] = "bear",
["enabled"] = false,
},
},
}
```
As of right now all is fine, however, lets say the mod developer wants to add a feature to their mod and needs to add a new item in …
=> feat(mod_config): Allow for nested config values for mods

src/game_object.lua
Cards in loc_vars for collection and so on are no longer nil, so custom consumeables are breaking. This should mimic consumeable set_ability behaviour close enough that they don't break.
=> fix: fake_card for consumeables

src/game_object.lua
When having a SMODS.Stake between the vanilla stakes, e.g.:
```lua
SMODS.Stake {
key = 'silver',
pos = {x = 0, y = 0},
applied_stakes = {'red'},
above_stake = 'red',
colour = G.C.GOLD,
loc_txt = {
name = "Silver Stake",
text = {}
},
prefix_config = {above_stake = {mod = false}, applied_stakes = {mod = false}},
}
```
Then the deck gets confused about its unlock stake (this is painted deck; it normally has the green stake as unlock):
=> Fix: fix deck unlock stake

src/ui.lua
Allows mod developers to use shadows in their mod description using `description_loc_vars`, if they want
=> Add shadow option to mod:description_loc_vars

src/utils.lua
[1404e](https://github.com/Steamodded/smods/commit/1189481445a3ddef598c978d67df78d0ac8e4ed6) added a default message for repetetions and joker retriggers. unfortanately, this default message is always applied, even if `remove_default_message` is specified. this pull request fixes that bug.
=> fix repetitions ignoring `remove_default_message`

src/utils.lua
This mainly just merges SMODS.deepfind and SMODS.deepfindbyindex into one singular function.
SMODS.deepfindbyindex still exists as a shorthand for backwards compatibility reasons.
The old syntax for calling SMODS.deepfind also still works, for the same backwards compatibility reason.
=> Improve SMODS.deepfind

lovely/booster.toml, src/game_object.lua
Fix a weird bug where modifying a Booster Pack's `ability.choose` value appears to work when viewing the pack's description but then doesn't actually work when opening the pack.
=> Booster Packs now respect changes to number of choices

lovely/fixes.toml
noticed a slight flaw where calling a pseudorandom in set_ability advances seeds while in the collection
kept this behaviour for to-do list, which, despite an attempted "fix" visible in card.lua, still has this issue in vanilla
=> fix seed advancing on collection

libs/https/luajit-curl.lua, libs/https/smods-https.lua, lovely/libs.toml
This adds a WIP implementation of the [https](https://love2d.org/wiki/lua-https) module that works cross platform without having to ship native libs. It uses one of 2 backends (the actual https module for windows, and libcurl for other platforms).
Basic example
```lua
local https = require "SMODS.https"
print(https.request("https://example.com"))
```
API differences from upstream lua https:
- Ships with a default user agent
- Additional checks on some values
- Proper error messages (curl backend only)
This has been tested on the following systems:
- Windows (via wine)
- Linux native build (Fedora 41)
- MacOS (Ventura intel)
Needs additional testing
- MacOS (No Xcode, No brew or other package manager) (Need to check if curl is actually provided by macos)
- ~~iOS (Not an offically support …
=> feat: cross-platform https

src/utils.lua
create_card polls for edition and applies it, if we're not disabling create_card edition poll behaviour when we're already going to force an edition, then a sound effect will potentially play due to two editions being applied
=> fix(create_card): Remove additional sound effect

lovely/blind.toml
Revert to prior behaviour which I erroneously removed.
=> Fix obj:set_blind() being called on reset

src/overrides.lua
This fixes hand size permanently increasing by 1 when using Death to turn a negative card non-negative.
(just a copy of the addition code later down in the function, but subtracting instead)
=> Fix set_edition not properly resetting negative playing cards

lovely/booster.toml, lovely/edition.toml, src/overrides.lua, src/utils.lua
- Fix gaining or discarding a negative playing card while it is debuffed adding/subtracting card limits
- Fix adding negative or any other card_limit increasing edition cards from booster pack to respective area not being allowed.
- Fix adding card_limit increasing edition cards that are not negative not being allowed from Buffoon or other Joker-yielding packs.
=> Fix a bunch of negative-related bugs

lovely/booster.toml
=> fix(select_card): select_card booster packs never add_to_deck on cards

lovely/better_calc.toml, lovely/can_calculate.toml, lovely/enhancement.toml, src/utils.lua
Due to how vanilla calculation is implemented, it can be difficult to remove or otherwise manipulate Cards during the main scoring phase, and perhaps some other moments. This PR aims to introduce a `Card:can_calculate` method that should enable modders to verify that a card can be expected to exist. This usage is accomplished in the following way:
1. Call `card:can_calculate(true)` to decide if an effect should be applied to/from the `card` (we'll explain the argument below);
2. Set `card.getting_sliced = true` when creating an Event that will remove or otherwise prevent a card from being calculated or "targeted" by other effects.
In addition to the aforementioned utility, the method also tests if the `card` object is debuffed or not. Thus, it can be used more generally to test if the …
=> Add Card:can_calculate

src/utils.lua
Fix a bug where if you play a High Card hand with five glass cards in the Fragile challenge, all of them break.
=> Revert a change to SMODS.calculate_destroying_cards to fix a bug related to glass cards

lovely/calculate_card_added.toml
Patches `Card:add_to_deck` to provide a new calculation context when adding (non-playing) cards to the deck. In addition to the card area, this context provides `context.card_added` (Boolean) and `context.card` (Card). A patch target is provided for mods that create new playing card types to exclude them manually.
I ran a simple test with a modded Joker that triggers when a Joker is obtained through any means, and it seems to work fine.
Documentation can be added if the PR is approved as is, or after changes are made.
=> Add context for adding cards to the deck

src/game_object.lua
Previously, the `prev` table is copied from the base `SMODS.Rank` object, which is a copy by reference and causes all Rank objects to have the same `prev` table.
This shifts the prev initialization to the `register()` function
=> Initialize prev table on register

lovely/better_calc.toml, lovely/blind.toml, lovely/blind_ui.toml, lovely/can_calculate.toml, lovely/enhancement.toml, lovely/seal.toml, src/overrides.lua, src/utils.lua
- Structural changes to functions processing calculations
- Reorganized `SMODS.calculate_context` using a helper function
- "Flags" returned by `SMODS.trigger_effects`
- `Card:can_calculate` is no longer called inside functions called from `eval_card`. `context.ignore_debuff` can be used to make debuffed cards be calculated in a context.
- Cards are no longer juiced up independently of the effect key in `SMODS.calculate_individual_effect` to account for new return values
- Added "individual objects" into the calculation pipeline. Deck effects have been integrated into this system. 
- Added the current blind as an individual object
- Added blind functions as calculation contexts: `blind_disabled`, `blind_defeated`, `press_play`, `debuff_card`, `debuff_hand`, `stay_flipped`, `modify_hand`
=> Better calc 2.3

lovely/center.toml, lsp_def/utils.lua, src/utils.lua
can now specify `t.bypass_discovery_center` and `t.discover` into SMODS.create_card to define those respective parameters when creating the Card. `bypass_discovery_center` is used for both `bypass_discovery_center` and `bypass_discovery_ui` to avoid excessive fields that all look the same but i'm not confident that that's the best approach
=> add discovery overrides to SMODS.create_card

src/game_object.lua
=> fix deprecated gradient warn crash

src/overrides.lua
prevents an issue where setting cards to negative during round end draws cards to the hand that doesn't exist
=> setting playing cards to negative only draws cards during blind

lovely/enhancement.toml
Game crash upon loading a new profile
Add a check within `set_ability` to make sure that `G.GAME.blind` exists before attempting to debuff cards. There's some gamestates where `set_ability` is called outside of a blind existing. 
`lovely/enhancement.toml`
* Added check for `G.GAME.blind` before calling upon it to debuff cards.
=> Fix to crash upon loading a new profile

src/utils.lua
In rare cases, the `cards` field of the `area` variable in `SMODS.find_card` can be nil, which causes a crash when calling `pairs(area.cards)`.
Crash example clip:
https://www.twitch.tv/edzyttv/clip/ColdAliveTruffleGingerPower-6tN0hLfSlknG8t_4
A simple nil check has been added to prevent the issue.
=> Fix crash when area.cards is nil in SMODS.find_card

lovely/edition.toml
Small fix to G.FUNCS.check_for_buy_space to allow cards with an edition that changes your card limit to be bought in the shop.
- [V] I didn't modify api's or I've made a PR to the [wiki repo](https://github.com/Steamodded/wiki).
- [V] I didn't modify api's or I've updated lsp definitions.
- [V] I didn't make new lovely files or all new lovely files have appropriate priority.
=> Fixed card_limit cards not being buyable at full room

src/card_draw.lua
Adds support for sticker rotation/offset for shiny stickers in SMODS.DrawStep by properly rotating/offsetting both the sticker itself and the "shiny" shader instead of only the sticker.
Also, this code was originally my badly implemented way to rotate/offset the sticker and can result in visual issues, so if there's a better method I don't know about let me know.
=> Add rotation/offset support for shiny stickers in SMODS.DrawStep

lovely/stake.toml
Vanilla `get_blind_amount` expects exactly 1, 2, 3, or nil; call `SMODS.get_blind_amount` for _any_ other value rather than only values exceeding 3. (e.g. decimal, negative, zero)
=> Better catch for non-vanilla scaling factors

src/overrides.lua
When I was programming my own suit I encountered this problem with deck preview numbers.
which does not match with what's being showin in deck view
So I made a small change by make the logic inside deck preview UI to consider the suit's icon defined in SMODS.Suit
Feel free to make changes to this PR and if this is not wanted feel free to close it.
=> Fix deck preview not using suit icon

lovely/fixes.toml
Prevents crash from Blue Seal attempting to create a non-existent planet card for a custom winning hand that lacks one. (Causes a random planet card to be rewarded instead.)
=> Blue Seal crash fix

lovely/poker_hand_screen.toml
Added as a third value to the examples
=> Add enhancements to poker hand tips

lovely/better_calc.toml
This allows for selectively deciding which card effects trigger in modify_scoring_hand when the blind checks if the hand should be debuffed (such as selecting a card in hand or just before scoring) vs when the final hand is actually decided. I believe a flag is better than a cardarea check because debuff_hand happens both in hand and in play, but maybe there's a better way.
=> Add in_scoring field to modify_scoring_hand context

lovely/poker_hand_screen.toml
Adds support for text formatting like in card descriptions to poker hand tips. 
The only detail is that `s` is based on the description scale of `0.32` instead of the poker hand tooltip scale of `0.4` so anything smaller than `{s:1.25}` will be smaller than normal text. And V and B are obviously not supported without `loc_vars`.
As far as I can find the only other place in vanilla that uses the patched function are these tooltips in deck view but they are unaffected.
=> Add text styling to poker hand tips

lovely/ui.toml, lsp_def/smods_core.lua, src/overrides.lua, src/ui.lua
Added SMODS.current_mod.ui_config to be able to customize the colours of the UI elements in a mod's menu. This could maybe be expanded to include the addition buttons or setting text scaling in the future.
=> Mod UI config

src/game_object.lua
Adds glass_trigger to destroyed Glass cards similar to lucky_trigger for Lucky cards. This allows checking if any glass shattered because of its own trigger in context.remove_playing_cards.
I've seen multiple devs asking how to do this on the Balatro server recently being recommended to use take_ownership and I've already seen it cause conflicts because multiple devs wanted to take_ownership for similar reasons but another mod did beforehand. For that, I think this would be a cool addition to SMODS.
I don't believe the flag has to be cleared as the card is removed after, but I could be wrong.
=> Add glass_trigger to Glass Cards destroyed by their own effect

lovely/shop.toml
Changes the edition polling to a call to poll_edition for Illusion
=> Allow modded editions for playing cards in shop

lovely/center.toml, lovely/pool.toml, src/utils.lua
Adds a function for mods to hook when the game checks for Showman to allow Showman-like effects. Additionally, it takes the key of the card to generate in order to be more granular with the effect.
Following #659 I've noticed updating [Vanilla Remade](https://github.com/nh6574/VanillaRemade) that Showman was the only joker to not have a graceful implementation using only SMODS and hooks (though the solution was simply to force the name to be "Showman")
=> `SMODS.showman()`

lovely/pool.toml, src/game_object.lua, src/overrides.lua
Added the ability to use `get_current_pool("Edition")` and modified `poll_edition` to use it. Also added `in_shop = true` to the vanilla editions for this change.
=> `get_current_pool` for editions

lovely/center.toml, src/utils.lua
Better handling of playing cards with SMODS.create_card and add_card. 
`set` now takes `Playing Card` for a random choice between `Base` and `Enhanced` and all three sets now default to `G.hand` as the `area` instead of `G.jokers`.
Additionally the following parameters are added:
`front`: Front of the playing card, formatted like `S_R`. Added to maintain a formatting similar to `create_playing_card` for those who need it. Ignores `rank` and `suit`.
`rank`: Takes both the `key` or the `card_key` (allows integers for vanilla ranks).
`suit`: Takes both the `key` or the `card_key`
`enhanced_poll`: To modify the chance of choosing `Base` or `Enhanced` with set `Playing Card`. Default: 0.6
`SMODS.add_card` adds to the `G.playing_card` counter and inserts the card into `G.playing_cards`. I …
=> (Better) Playing card support for SMODS.create_card

src/game_object.lua
Adds an `object_types` field when a Center is inserted into an ObjectType to easily look up what types it belongs to.
=> Add lookup table of ObjectTypes to each center

src/utils.lua
Adds `SMODS.merge_effects` that takes any number of arrays of tables and nests them using the `extra` field. 
Useful primarily for copying multiple cards with `SMODS.blueprint_effect`.
=> Add util function for merging calculate return tables

lovely/pool.toml
I'm tired of this one :)
Even the LSP says it does when it doesn't lol
=> Allow `pseudorandom_element` to take strings for seeds

lovely/gradient.toml
Fixes gradients causing a stack overflow when used for messages and other functions that use `attention_text`.
This fix would probably need to be applied in the future to other places that use `copy_table` to copy colours such as the text inputs.
=> Fix `SMODS.Gradient` crashing in `attention_text`

src/utils.lua
When leveling up a different hand than the one played during scoring all values revert back correctly except for the level. This PR fixes that problem.
=> Fix `smart_level_up` not updating level in scoring

src/utils.lua
Slight change to the SMODS.calculate_effect function to make some cards stop juicing wrong
=> Better calc individual juice fix (Issue #711)

lovely/enhancement.toml, src/card_draw.lua, src/utils.lua
Fixed an annoying bug with enhanced playing cards that are supposed to have hidden fronts, like Stone Cards, having those fronts be shown just before the enhancement is changed; for example, when Vampire removes the enhancement. It is also much easier to make card enhancements hide the front of the card by overriding the new Card:should_hide() function.
(Any other changes are because I made this with the beta-0614a build; my sincerest apologies for not really knowing what I'm doing GitHub-wise.)
=> Front Hiding Revamp

lovely/better_calc.toml
Adds a new value to context.end_of_round to provide a simpler way to check if a boss blind has just been defeated
=> Add beat_boss to context.end_of_round

src/utils.lua
To avoid some nil checks when passing the returns of SMODS.blueprint_effect directly
=> Type check in `SMODS.merge_effects`

lovely/better_calc.toml
Allows access to a blind's associated tag (if any) via setting_blind context
=> Make blind's tag object accessible outside of skipping

src/utils.lua
- Includes the `numerator` and `denominator` of the called `pseudorandom_probability()` in `context.pseudorandom_result`
That's all really, would allow for specific responses to specific odds in the context
=> Include numerator and denominator in context.pseudorandom_result

src/utils.lua
Prevents a nil crash.
Adds assertion for more clarity about why it crashes when it does crash.
=> Avoid crashes in SMODS.is_pokerhand_visible and add assert

src/loader.lua
Just a simple fix for a regression introduced in [`16165a3 (new mod menu)`](https://github.com/Steamodded/smods/commit/16165a3553e37489a3de4d8d433a4d8a5f8a2463#diff-aedf8f5b9a90b1617b8c21a8135ba671ca8149e0ae8ad8876db689dc6e6a3297) which causes `G.FUNCS.openModUI_<MOD-NAME>` functions to crash when called without argument.
Tested with all new mod menu buttons and a variety of other config mods without issue.
Motivated by https://github.com/Breezebuilder/SystemClock/issues/4
=> Add basic safety checks to `e.config.page` access and `LAST_SELECTED_MOD_TAB` assignment

src/ui.lua
Allow the user to register their modicon with a number of frames and the 'ANIMATION_ATLAS' atlas_table to allow it to be animated in the mod menu
=> Support animated Mod Icons

src/utils.lua
=> Prevent calculate_context from being called outside of a run (Closes #849)

src/utils.lua
Calling `smart_level_up_hand()` while the hand display text is set to '????' due to cards being played while face-down would cause the function to incorrectly re-set the hand display text values after leveling up the given poker hand. This PR fixes the issue.
Relevant issue: #756
=> Fix smart_level_up_hand() not properly updating hand text for hands with face-down cards

lovely/better_calc.toml, lovely/booster.toml, src/overrides.lua, src/utils.lua
- Calculates `context.money_altered` when money is earned or lost by hooking `ease_dollars()`.
- I've also included `G.STATES.SMODS_REDEEM_VOUCHER = 998` for when a voucher is redeemed (since previously it would be considered `G.STATES.PLAY_TAROT`, which made it very difficult to separate the two)
`context.money_altered` also includes some built-in checks for roughly determining the source of the change in money,
(ex: `context.from_shop` checks for shop transactions)
though these are not strictly necessary.
```
if context.money_altered then
{
amount = mod,
from_shop = (G.STATE == G.STATES.SHOP or G.STATE == G.STATES.SMODS_BOOSTER_OPENED or G.STATE == G.STATES.SMODS_REDEEM_VOUCHER) or nil,
from_consumeable = (G.STATE == G.STATES.PLAY_TAROT) or nil,
from_scoring = (G.STATE == …
```
=> Add context.money_altered (and G.STATES.SMODS_REDEEM_VOUCHER)

lsp_def/classes/blind.lua, lsp_def/classes/booster.lua, lsp_def/classes/center.lua, lsp_def/classes/edition.lua, lsp_def/classes/enhancement.lua, lsp_def/classes/poker_hand.lua, lsp_def/classes/rank.lua, lsp_def/classes/rarity.lua, lsp_def/classes/seal.lua, lsp_def/classes/sticker.lua, lsp_def/classes/suit.lua, lsp_def/smods_core.lua, lsp_def/utils.lua, lsp_def/vanilla.lua
* Added vanilla Enhancements, Editions, Seals, Stickers, Rarities, Ranks, Suits and PokerHands definitions and added it to the relevant type hints in functions
* Added internal card area types (jokers, playing card, individual) definitions
* Fix Mod.ui_config type
* Added 'prevent_debuff' to SMODS.debuff_card
* Update get_probability_vars/pseudorandom_probability definitions
* Updated loc_txt for multiline names and multibox descriptions
=> Miscellaneous LSP updates

lovely/ui.toml, lsp_def/classes/consumable_type.lua, src/game_object.lua, src/ui.lua
It was brought to my attention earlier today that ConsumableTypes don't actually do anything with their primary_colour definitions; I dug around in the code for a little while, but couldn't find much of anything that uses it directly or via the `G.C.SET[type_key]` definition. (there is one place where I saw it used, but I don't see any visual differences from my changes) As such, I decided that it might be useful to actually make it do something. This coincides with my work on a new consumable set of my own, which I wanted to use a white background and black text for.
ConsumableType objects now take a `text_colour` and a `bg_colour` parameter, instead of `primary_colour` and `secondary_colour`. `bg_colour` is used for the color of the consumable type's badge and its UI button in the …
=> ConsumableType: change primary/secondary color to text/bg color

src/game_object.lua, src/utils.lua
* Allows type to take other values
* Allows decks quip_filter to return pool_opts
* quip_filter for mod objects, priority for pool_opts goes mods > deck > quip
=> `JimboQuip` changes

lovely/booster.toml, src/game_object.lua
PR to add `G.GAME.modifiers.booster_choice_mod`; can be modified to alter the amount of available choices you can make in a booster pack (ex. Choose 2 of 5 -> Choose 3 of 5)
Automatically adjusts to not exceed the size of the pack and also handles the pack's `loc_vars`
=> Add G.GAME.modifiers.booster_choice_mod

lsp_def/utils.lua, src/utils.lua
Added parameter to create_card/add_card to allow duplicates when using a set that doesn't allow them without needing Showman.
Plus some other updates to the SMODS.create_card LSP definition.
=> `allow_duplicates` in `SMODS.create_card`

lovely/back.toml
Added a missing `Back.load` call when the game starts. This allows saving values to `back.effect` similar to `card.ability`.
=> Add deck loading when reloading a run

src/overrides.lua
Title, add a context that runs when setting an ability. Flags include the `card` that was affected, the `old_center` of the card, and an `unchanged` boolean that is true if the card's old_center is identical to the "new" one
=> setting_ability Context

src/utils.lua
Only recalculates the Operator when either text or colour is a function
=> Only recalculate Operator when needed

src/overrides.lua
+Title, this was lost in the original merge
I think `Card:calculate_joker()` is still getting called outside of other context evaluations, so I'm adding this back for consistency.
(Else the `context_stack` might not get updated)
=> Added missing `Card:calculate_joker()` hook for `SMODS.context_stack`

lovely/center.toml, lovely/jimboquip.toml, src/game_object.lua, version.lua
Adds more arguments to JimboQuip's extra table:
- `sound`: takes a sound key `string` or a `table` of sound key `strings`; allows custom sound(s) for card "voice"
- `times`: takes a `number`; allows custom number of times the card will "speak"
- `delay`: takes a `number`; allows custom timing between speaking events
- `juice`: takes a `table` of `numbers` (i.e. `{0.6, 0.6}`); allows custom juicing of the card for its speaking events
- `pitch`:  takes a `number`; allows custom set pitch for the "voice"
=> Expanded JimboQuip extra

lovely/fixes.toml, version.lua
=> Allow `pseudoshuffle` to take a string as a seed

lovely/better_calc.toml, lsp_def/utils.lua, src/utils.lua
*Title, what I mean by "Getter" context is any of these contexts (currently), `mod_probability`, `fix_probability` and `check_enhancement` (and `get_ranks` if Quantum Ranks gets merged)
This fix checks the following before `eval`ing any object (currently only during the `SMODS.calculate_card_areas` of a complete `SMODS.calculate_context` call, no external `eval` calls).
(The example uses Quantum Rank stuff but this problem occurs with just Quantum Enhancements too)
Example:
Joker A: All lucky cards count as 7s
Joker B: All 7s count as lucky cards
Joker A is eval'd in a `get_ranks` context, calls `SMODS.has_enhancement()` and causes a `check_enhancements` context
Joker B is then eval'd, calls `Card:is_rank()` and causes a `get_ranks` context
The game gets stuck in an infinite loop and …
=> Fixed infinite "Getter" context loops

src/utils.lua
Crashes this fixes:
- Crash when passing the `cards` field of an empty CardArea (if a modder wanted to destroy every card in that area)
- Crash when passing a table containing a nil result from pseudorandom_element (if a modder wanted a random card in that area)
Other than preventing these crashes, this has no additional effect.
=> make destroy_cards not crash when passed an empty table

lovely/card_limit.toml, src/utils.lua
*Title
Fixes #965 
There's an issue when drawing negative playing cards after discarding; 
Two cards are drawn instead of one. I don't know where the second one's coming from.
=> Fixed incorrect hand size when reloading with `negative` playing cards in hand

lovely/blind.toml, lovely/pool.toml, src/overrides.lua
Some functions ignore `SMODS.add_to_pool` if the object doesn't have `in_pool` defined.
=> Fix `SMODS.add_to_pool` being ignored

lovely/scoring_calculation.toml, src/game_object.lua, src/utils.lua
* 1st commit: The way `SMODS.scoring_parameter` injects itself into `update_hand_text` doesn't remove `chips` and `mult`'s vanilla behavior, so I'm excluding those from the loop. I've tested and they should work without further problems.
* 2nd commit: The API injection at runtime makes some of the elements in `G.hand_text_area` refer to orphaned tables (Object nodes that no longer store an object due to it being overridden), therefore I'm making a new function that refreshes `chips` and `mult` as well as adding new scoring parameters if applicable.
* 3rd commit: Back to 1st commit, the previous injection makes `mult` behave inconsistently with the juice effect. It is restored now, but I feel like this could be expanded, so I'm adding a new argument for the `vals` table in …
=> Small tweak and expansion to Operator API
