Steamodded/smods

core/sprite.lua
core/suit.lua

This was made based on my previous Six Suits mod, with the purpose of making different playing card mods compatible with each other. The current version is incomplete, as some effects like strength or randomizers like sigil still need to be adapted. While I work on finalizing these and writing proper docs, you may test the current version over on my fork and report any bugs and crashes you encounter.

Playing card API

---

steamodded_injector.py

Patch core load order to avoid crash on Mac and Linux

Patch load order

---

README.md

Updates the command to correctly hand off the Balatro executable as the SFX file that is being edited.

Update the Linux install command

---

README.md

Amended from my personal experience installing Steamodded

Update MacOS install instructions

---

injector.ps1

Using technique described here: [Find steam games folder](https://stackoverflow.com/questions/34090258/find-steam-games-folder)

Support more reliable way to find game location from steam library.

---

core/joker.lua

not on production main this time :balatrojoker:

Add blueprint and eternal compatibility support to Joker API

---

debug/debug.lua
debug/tk_debug_window.py

Optimize log buffering and processing in `client_handler` for enhanced efficiency and better log parsing.
Also implement an "export log" functionality, requested by @itayfeder on discord

Debug console: Implement log "buffer" handling in client socket handler

---

debug/debug.lua

This PR makes it where the debug methods also print to the lua console. This is useful for cases where there is a debug console (such as with lovely), where one does not need to run steamodded's debug console.

Print on debug msg

---

core/core.lua
core/deck.lua
core/joker.lua
core/planet.lua
core/r_blind.lua
core/seal.lua
core/spectral.lua
core/sprite.lua
core/tarot.lua
core/voucher.lua
loader/loader.lua

Reuses the game's debug logic to print the progress of Steamodded's initialization when it loads.

Print loading progress when booting

---

core/game_object.lua
lovely/playing_card.toml

I forgot I was making these on a fork for some reason

Stake API and erratic deck bugfix

---

lovely/payout_arg.toml

Please believe me, this API was tested before release.

Fix crash + incorrect colour in Payout Arg API when trying to display negative dollars

---

core/overrides.lua

these other commits are useless but I don't know how to remove them (:

Fix duplicate edition sound bug

---

core/core.lua
core/game_object.lua
core/overrides.lua
core/utils.lua
lovely/blind.toml
lovely/blind_ui.toml

need a bit more testing likely

allow blinds' loc_txt to have more than 2 lines

---

core/game_object.lua
example_mods/Mods/TestKeybinds.lua
lovely/keybind.toml

This will add ability to create keybinds. For now keybinds will only run on key press, but it's possible to add support for key release and hold (not sure how necessary this is, so didn't feel like adding it yet).
Includes an example mod to showcase the new functionality.

Add keybinds API

---

core/game_object.lua
example_mods/Mods/LabyrinthDeck.lua
lovely/back.toml
lovely/seal.toml

- Add support for `loc_vars` on Backs (should this be extended to allow `generate_ui` too?)
- Add support for `loc_vars` on Seals
TODO:
- Is loc_vars support missing anywhere else?

Extend support for loc_vars

---

core/game_object.lua
lovely/back.toml
lovely/seal.toml
lovely/sticker.toml

This seems very awkward to make work, each custom rule is its own localization entry, with a single loc var. Looks like ideally we support multiple loc vars for each rule.
Challenges don't seem like a priority right now

Loc vars 1

---

example_mods/Mods/EditionExamples/EditionExamples.lua
example_mods/Mods/EditionExamples/README.md
example_mods/Mods/EditionExamples/assets/shaders/anaglyphic.fs
example_mods/Mods/EditionExamples/assets/shaders/flipped.fs
example_mods/Mods/EditionExamples/assets/shaders/fluorescent.fs
example_mods/Mods/EditionExamples/assets/shaders/foil.fs
example_mods/Mods/EditionExamples/assets/shaders/gilded.fs
example_mods/Mods/EditionExamples/assets/shaders/greyscale.fs
example_mods/Mods/EditionExamples/assets/shaders/ionized.fs
example_mods/Mods/EditionExamples/assets/shaders/laminated.fs
example_mods/Mods/EditionExamples/assets/shaders/monochrome.fs
example_mods/Mods/EditionExamples/assets/shaders/overexposed.fs
example_mods/Mods/EditionExamples/assets/shaders/sepia.fs

Better shaders explanation
remove unnecessary functions (mostly RGB and HSL, where they're not used)
fix flipped shader (it never worked)
improve readme

Example Editions mod improvements

---

core/utils.lua
loader/loader.lua

Stops mod badges from being scaled down in height when the name is long.
Added `TEXT_COLOUR` argument to mod headers to set the mod badge text colour.
*ignore the shader crap my git is screwed up (:*

Mod badge height fix

---

lovely/fixes.toml

Support add_to_deck/remove_from_deck on set_ability overriding previous center

---

core/core.lua
core/utils.lua
json/init.lua
json/json.lua
lovely/json.toml

Added JSON parsing of localization files using [json.lua](https://github.com/rxi/json.lua).
Logic-wise, Steamodded first checks for Lua files so if there's both `default.json` and `default.lua`, the Lua variant takes priority.

Implement JSON parsing of localization files

---

lovely/atlas.toml
lovely/seal.toml
lovely/ui_elements.toml

Allows for multiple text_inputs to exists by giving them an `id`.
Also fixes tab colours not being implemented, some additional seal functionality, and undiscovered sprite no overlay option.

Text Input Fixes

---

core/game_object.lua
localization/zh_CN.lua
lovely/sound.toml

Sound API currently has issues playing music and bypasses the modulate functionality completely. This integrates it with the sound manager at hand.

Convert sound API to using sound_manager

---

core/core.lua
core/game_object.lua
lovely/sound.toml

Fix consecutive plays of the same sound

Fix sound bug

---

core/ui.lua

Fixes mod checkboxes toggling when switching pages and the game doesn't restart if you put all checkboxes back to their default state

feat: better mod toggling

---

core/ui.lua
loader/loader.lua
localization/en-us.lua
localization/es_419.lua
localization/es_ES.lua
localization/zh_CN.lua

feat: show prefix conflicts in ui

---

config.lua
core/ui.lua
localization/en-us.lua
lovely/menu.toml

4 by default is optimal from my testing

Add mipmap to graphics settings

---

core/game_object.lua
core/overrides.lua
lovely/center.toml
lovely/enhancement.toml

Fixes a few errors with enhancement calculation and ensures joker calculation only calculates jokers

Fix enhancement calculation

---

lovely/joker_retrigger.toml
lovely/playing_card.toml

Some of these patches never worked, so I removed them completely. Making them work only causes issues.
Other patches didnt work properly with latest lovely, so I combined them.

Retrigger API fixes

---

core/overrides.lua

also remove wonky spacing logic from vanilla

dynamically display ante in collection during a round

---

localization/en-us.lua
localization/es_419.lua
localization/es_ES.lua
localization/zh_CN.lua

+ Translated multiple Chinese localization placeholders
+ Added placeholder entries for `b_stickers` and `b_graphics_mipmap_level` in both Spanish localizations - if someone can translate these, please do!
+ Cleaned up the indentation in all 4 localization files

localization improvements

---

lovely/playing_card.toml

I've gotten the occasional crash on the enhancements collection for trying to read rank.face but rank is nil. I assume some weird mod interaction.

safety check for rank

---

lovely/fixes.toml

Since a few mods want to patch these parts of Card:draw, I thought it would make sense if this was common in steamodded

Improve Card:draw()

---

core/ui.lua
loader/loader.lua
lovely/menu.toml

feat: alert on mods button

---

core/game_object.lua
lovely/rarity.toml

ObjectType/Rarity API bugfixes

---

core/utils.lua

Found the issue because I was playing with BetterFR (https://github.com/FrBmt-BIGetNouf/balatro-french-translations), that changes all vanilla strings in a specific language, and one of the latest Steamodded commits broke it (and displayed vanilla balatro's french translation, which is passable at best and broken at worse)
The solution was quite simple, make the locale loading force-replace strings for the selected language
Hope this gets merged quickly!

Fix for localization patching mods

---

loader/loader.lua

Fixed mods that use DeckSkin being falsely flagged as outdated

Fix DeckSkin outdated false flag

---

core/game_object.lua
core/utils.lua

insert another clown emoji here

Yet Another Rarity API Bugfix

---

lovely/center.toml

Hidden Consumables now respect in_pool

hidden consumables fix

---

README.md
example_mods/Mods/EditionExamples/README.md
src/crash_handler.lua

Sorry if this comes off as nitpicky or annoying, but I feel like it's important to get right:
The framework is called LÖVE, and the url for it is love2d.org. 'LÖVE2D' and 'Love2D' aren't right, nor is it an engine.

Correct mentions of LÖVE

---

lovely/back.toml
lovely/joker_retrigger.toml

Since the vanilla game has only 2 contexts in which the Back:trigger_effect() func is called I piggybacked off of the joker contexts to add a bunch of new contexts.

Add a bunch of joker contexts as deck contexts as well

---

src/utils.lua

quantum enhancements nil check

---

lovely/back.toml
lovely/enhancement.toml
lovely/joker_retrigger.toml
lovely/sticker.toml
src/game_object.lua
src/utils.lua

Sticker calc is really basic and can't be stacked with joker effects in evaluate_play. I'm trying to fix this through consistent usage through eval_card. This is currently incomplete, thinking about rewriting evaluate_play with better util functions to take care of that

[WIP] sticker calc

---

lovely/fixes.toml

kinda dumb to do another pr for this, it's just fixing the hand cards check because i forgot

fix the other way to softlock in boosters

---

lovely/sticker.toml

stickers are being drawn a bit too late (on top of floating sprites)

move sticker draw layer

---

lovely/better_calc.toml
src/utils.lua

Purple seals
Correcting jokers juicing played cards
half-fixed baseball card

More fixes

---

lovely/rarity.toml

allow base game rarities to be used as strings in get_current_pool

---

lovely/enhancement.toml
src/utils.lua

it's very unclean and shouldn't be done this way, but i'm honestly just trying to bring a bit of attention towards it

basic enh cache that probably doesn't break

---

src/utils.lua

find_card in vouchers

---

localization/pt_BR.lua

Hi! I thought I might as well translate steamodded itself if I'm translating mods. I kept it as close to the original en-us as possible

Add Brazilian Portuguese localization

---

localization/fr.lua

Thought I might as well add localization for this since I'm working on another mod.
Based on Balatro's official localization, meaning words like "seed" aren't translated. "Mipmap" also doesn't have a real french equivalent.

Add french localization

---

src/game_object.lua

Fix celestial packs

---

lovely/shop.toml

fixes https://www.youtube.com/watch?v=xNtl_ynNokQ

save shop_voucher

---

lovely/perma_bonus.toml

Fix all other mult granting enhancements that aren't just Mult Card

---

tk_debug_window.py

This is mainly a "fix" for Linux, as DPI scaling doesn't seem to work well. The default behavior remains as is, but with a `--scale` or `-s` flag, the console font scaling changes.
Also made [this](https://github.com/Steamodded/Wiki/pull/18) Wiki PR

Added an argument to the debug console that controls the font scaling.

---

localization/ko.lua

Localizes strings into Korean.

Add Korean localization

---

lovely/enhancement.toml
lovely/fixes.toml
src/utils.lua

- Fixed bug where Smeared Joker would count any modded suit as a Club or Spade
- Fixed bug that prevented hands with Clubs and all other modded suits from getting a X2 with Seeing Double

Smeared Joker and Seeing Double bug fix with Modded Suits

---

lovely/playing_card.toml

add gradients to LOC_COLOURS

---

lsp_def/utils.lua
src/utils.lua

Function behaviour should stay the same.

Swap card <-> blueprint_card in blueprint_effect function

---

src/overrides.lua

fix crash without wins_by_key

---

libs/https/smods-https.lua
lovely/fixes.toml
src/crash_handler.lua
src/game_object.lua
src/loader.lua
src/overrides.lua
src/ui.lua
src/utils.lua

Makes currently existing asserts provide explicit error indicating problems, rather than leaving them blank. Additionally considering updating older ones for style.

More Explicit Asserts

---

localization/es_419.lua
localization/es_ES.lua

Update es_ES and es_419 localizations

---

localization/ru.lua

Russian localization

---

localization/it.lua

Added an Italian localization for smods.
- [✓] I didn't modify api's or I've made a PR to the [wiki repo](https://github.com/Steamodded/wiki).
- [✓] I didn't modify api's or I've updated lsp definitions.
- [✓] I didn't make new lovely files or all new lovely files have appropriate priority.

Italian localization

---

lovely/better_calc.toml

(Obviously not ideal and probably an issue with some mod but I couldn't figure out which one)
Should fix the below crash when playing a hand with these jokers:
https://github.com/user-attachments/assets/36e75029-4068-4fea-8436-162f8dd2a265
```
INFO - [G] 2025-05-19 20:55:28 :: ERROR :: StackTrace :: Oops! The game crashed
functions/common_events.lua:775: attempt to call method 'can_calculate' (a nil value)
Stack Traceback
===============
(1) Lua local 'handler' at file 'main.lua:612'
Local variables:
msg = string: "functions/common_events.lua:775: attempt to call method 'can_calculate' (a nil value)"
(*temporary) = Lua function '?' (defined at line 31 of chunk [SMODS _ "src/logging.lua"])
(*temporary) = number: 2.2932e-314
(*temporary) = string: "Oops! The game crashed\
"
(2) LÖVE method …
```

fix crash when `context.other_card.can_calculate` is `nil`

---

lovely/better_calc.toml

It adds the Anaglyph context to the regular calculation pipeline.

context.round_eval

---

lovely/better_calc.toml
lsp_def/utils.lua
src/utils.lua

Adds a function that calculates whether or not a card is considered eternal.
Also adds context.check_eternal for that calculation.

`SMODS.is_eternal`

---

src/utils.lua

Fix vanilla playing card rng with `SMODS.create_card`

---

lovely/seal.toml

Removes a patch from seal.toml that's done earlier in better_calc.toml

Remove unnecessary patch from seal.toml

---

lovely/better_calc.toml
src/overrides.lua
src/utils.lua

This PR takes the concepted pseudorandom_result context and gives it better timings as well as support for consumables (I have no clue why these commits are so weird as most of them were already pulled 💀)

pseudorandom_result context handling

---

lovely/better_calc.toml
lovely/jimboquip.toml
src/game_object.lua
src/utils.lua

Added a new GameObject, SMODS.JimboQuip which serves to allow mods to easily add new quips for Jimbo to say on run wins/losses. All you need is a key and a type set to 'win' or 'loss', as well as a loc_txt table or matching entry in a localization file.
Quips can be filtered out or increase their chance of appearing with the filter function. Additionally, you can set an extra table (or function that returns a table) to specify extra details like changing the center of the card character or the colors of its materialization or particles.
Decks can also filter out quips with an added quip_filter function to SMODS.Back. This allows certain decks to only show certain quips. quip_filter is called at the same time as filter is for every quip that can be added to the pool, and functions …

Added SMODS.JimboQuip

---

localization/en-us.lua
lovely/better_calc.toml
lovely/listed_probabilities.toml
lovely/perma_bonus.toml
src/game_object.lua
src/utils.lua

+Title, this allows playing cards to gain permanent retriggers. 
+(Localization added too)
First contribution yipee! Please leave feedback if you have any :)

Added perma_repetitions to perma_bonus.toml

---

lsp_def/classes/back.lua
lsp_def/classes/consumable.lua
lsp_def/classes/gradient.lua
lsp_def/classes/jimbo_quip.lua
lsp_def/classes/joker.lua
lsp_def/classes/voucher.lua
lsp_def/smods_core.lua
lsp_def/utils.lua

* Some changes to SMODS.Gradient
* SMODS.JimboQuip definition
* Add quip_filter to SMODS.Back
* Scaling values function definitions and type hint change to SMODS.scale_card
* context.money_altered definitions

LSP Updates for 0808a

---

lovely/better_calc.toml

Fixed Campfire "Upgrade" attention text when selling it.

---

src/card_draw.lua

Use Card:should_hide_front() in DrawStep code

---

lovely/center.toml
lovely/fixes.toml
lovely/multi_box_descriptions.toml
lovely/ui.toml
lovely/ui_additional_text_props.toml
src/game_object.lua
src/utils.lua

This also includes the previous patch I made, by the way! (it's for the checking the info_queue flag)
https://github.com/Steamodded/smods/pull/836

info_queue's stylized name + multi lines name support

---

lovely/blind.toml
lovely/center.toml
lovely/fixes.toml
lovely/playing_card.toml
lovely/pool.toml
lsp_def/utils.lua
src/overrides.lua
src/utils.lua

Adds a helper function other mods can hook to check whether an object is in the pool.

`SMODS.is_in_pool()`

---

lsp_def/smods_core.lua
src/utils.lua

I don't believe this should be an optional feature but I haven't stress-tested it with a lot of mods.

Global mod `calculate`

---

lsp_def/classes/stake.lua
src/game_object.lua
src/utils.lua

Added calculate function to stakes, calculated from lowest order to highest order.

Stake `calculate`

---

lovely/ui.toml

Mods menu restarts after changes when pressing esc (Fixes #616)

---

localization/es_419.lua
localization/es_ES.lua

Update `es_419.lua` and `es_ES.lua`

---

src/game_object.lua

Unlike the rest, this local function did not receive a proper revamp.

Use `SMODS.shatters` in local `random_destroy`

---

src/utils.lua

Similar to how the probability contexts update the numerator and denominator.

Update `amount` in `context.drawing_cards`

---

lsp_def/utils.lua

Ante and setting ability contexts lsp definitions
